---
- name: Setup PostgreSQL Master
  hosts: master
  tasks:

    - name: Ensure postgres user exists
      ansible.builtin.user:
        name: postgres
        shell: /bin/false
        home: /var/lib/postgresql
        system: yes
        create_home: yes

    - name: Install PostgreSQL 16 and psycopg2
      apt:
        name:
          - postgresql-16
          - python3-psycopg2
          - pgbouncer
          - python3-passlib
        state: present
        update_cache: yes

    - name: Configure postgresql.conf for replication
      template:
        src: postgresql.conf.j2
        dest: /etc/postgresql/16/main/postgresql.conf
      notify: Restart PostgreSQL Master

    - name: Configure pg_hba.conf for replication and clients
      blockinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        block: |
          # Allow replication from slave
          host  replication {{ replication_user }} {{ slave_ip }} md5
      notify: Restart PostgreSQL Master

    - name: Wait for PostgreSQL socket to be ready
      wait_for:
        path: /var/run/postgresql/.s.PGSQL.5432
        state: present
        timeout: 30

    - name: Set password for default postgres user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: "SUPERUSER,CREATEDB,CREATEROLE,LOGIN"
        login_unix_socket: /var/run/postgresql

    - name: Create replication user
      become_user: postgres
      postgresql_user:
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        role_attr_flags: "REPLICATION,LOGIN"
      

    - name: Create user Kamailio
      become_user: postgres
      postgresql_user:
        name: "{{ kamailio_user }}"
        password: "{{ kamailio_password }}"
        role_attr_flags: CREATEDB,NOSUPERUSER

  handlers:
    - name: Restart PostgreSQL Master
      service:
        name: postgresql
        state: restarted