- name: Install pgbouncer
  apt:
    name: pgbouncer
    state: present
    update_cache: yes

  
- name: Deploy pgbouncer.ini from template
  template:
    src: bouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: pgbouncer
    group: pgbouncer
    mode: '0644'
  notify: restart package


- name: Generate userlist.txt
  copy:
    dest: /etc/pgbouncer/userlist.txt
    content: |
      {% for u in pgbouncer_users %}
      "{{ u.name }}" "{{ u.password }}"
      {% endfor %}
  notify: restart package