- name: Install Kamailio
  apt:
    name: 
      - kamailio
      - kamailio-postgres-modules
    state: present
    update_cache: yes

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/kamailio.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure systemd override for Kamailio runtime directory
  copy:
    dest: /etc/systemd/system/kamailio.service.d/override.conf
    content: |
      [Service]
      RuntimeDirectory=kamailio
      RuntimeDirectoryMode=0755
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart kamailio

- name: Deploy kamailio.cfg
  template:
    src: kamailio.cfg.j2
    dest: /etc/kamailio/kamailio.cfg
  notify: restart kamailio

- name: Demploy kamctlrc
  lineinfile:
    path: /etc/kamailio/kamctlrc
    regexp: "^#?DBENGINE=MYSQL"
    line: "DBENGINE=PGSQL"
  notify: restart kamailio

