- name: Install Kamailio
  apt:
    name: 
      - kamailio
      - kamailio-postgres-modules
    state: present
    update_cache: yes

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/kamailio.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure systemd override for Kamailio runtime directory
  copy:
    dest: /etc/systemd/system/kamailio.service.d/override.conf
    content: |
      [Service]
      RuntimeDirectory=kamailio
      RuntimeDirectoryMode=0755
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart kamailio

- name: Deploy kamailio.cfg
  template:
    src: kamailio.cfg.j2
    dest: /etc/kamailio/kamailio.cfg
  notify: restart kamailio

- name: Demploy kamctlrc
  lineinfile:
    path: /etc/kamailio/kamctlrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
  - { regexp: '^#?DBENGINE', line: 'DBENGINE=PGSQL'}
  - { regexp: '^#?DBHOST', line: 'DBHOST=127.0.0.1'}
  - { regexp: '^#?DBPORT', line: 'DBPORT=5432'}
  - { regexp: '^#?DBNAME', line: 'DBNAME=appdb'}
  - { regexp: '^#?DBRWUSER', line: 'DBRWUSER=kamailio'}
  - { regexp: '^#?DBRWPW', line: 'DBRWPW=supersecret'}
  - { regexp: '^#?DBROUSER', line: 'DBROUSER=kamailio'}
  - { regexp: '^#?DBROPW', line: 'DBROPW=supersecret'} 
  notify: restart kamailio


- name: Create .pgpass for postgres user
  ansible.builtin.copy:
    dest: /var/lib/postgresql/.pgpass
    content: "127.0.0.1:5432:appdb:{{ db_user }}:{{ db_password }}\n"
    owner: postgres
    group: postgres
    mode: '0600'

- name: Check if Kamailio schema already initialized
  community.postgresql.postgresql_query:
    db: "{{ kamailio_db_name }}"
    query: "SELECT 1 FROM information_schema.tables WHERE table_name='subscribers';"
  become_user: postgres
  register: kamailio_schema_check
  failed_when: false

- name: Init Kamailio schema (direct to Postgres)
  command: "/usr/sbin/kamdbctl create {{ kamailio_db }}"
  environment:
    DBPORT: "5432"
  become: yes
  become_user: postgres
  when: kamailio_schema_check.query_result[0] is not defined

# Setelah schema dibuat, ubah koneksi runtime ke PgBouncer
- name: Configure kamctlrc for runtime (via pgbouncer)
  lineinfile:
    path: /etc/kamailio/kamctlrc
    regexp: '^#?DBPORT'
    line: 'DBPORT=6432'
  notify: restart kamailio



